DO $$
DECLARE
    v_email VARCHAR(100) := '566217';
    v_designation VARCHAR(100) := 'HO-TOPMGMT';
BEGIN
INSERT INTO role_reports (
    created_date,
    updated_date,
    active,
    email,
    is_admin,
    mode,
    reportid,
    role_id,
    sequence,
    transition
)
VALUES
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP1',  v_designation, 1, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP2',  v_designation, 2, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP3',  v_designation, 3, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP4',  v_designation, 4, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP5',  v_designation, 5, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP6',  v_designation, 6, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP7',  v_designation, 7, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP8',  v_designation, 8, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP9',  v_designation, 9, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP10',  v_designation, 10, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP11',  v_designation, 11, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP12',  v_designation, 12, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP13',  v_designation, 13, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP14',  v_designation, 14, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP15',  v_designation, 15, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP16',  v_designation, 16, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP17',  v_designation, 17, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP18',  v_designation, 18, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP19',  v_designation, 19, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP20',  v_designation, 20, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP21',  v_designation, 21, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP22',  v_designation, 22, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP23',  v_designation, 23, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP24',  v_designation, 24, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP25',  v_designation, 25, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP26',  v_designation, 26, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP27',  v_designation, 27, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP28',  v_designation, 28, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP29',  v_designation, 29, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP30',  v_designation, 30, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP31',  v_designation, 31, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP32',  v_designation, 32, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP33',  v_designation, 33, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP34',  v_designation, 34, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP35',  v_designation, 35, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP36',  v_designation, 36, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP37',  v_designation, 37, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP38',  v_designation, 38, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP39',  v_designation, 39, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP40',  v_designation, 40, 15),
    -- SKIPPED: RP41
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP42',  v_designation, 41, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP43',  v_designation, 42, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP44',  v_designation, 43, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP45',  v_designation, 44, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP46',  v_designation, 45, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP47',  v_designation, 46, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP48',  v_designation, 47, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP49',  v_designation, 48, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP50',  v_designation, 49, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP51',  v_designation, 50, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP52',  v_designation, 51, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP53',  v_designation, 52, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP54',  v_designation, 53, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP55',  v_designation, 54, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP56',  v_designation, 55, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP57',  v_designation, 56, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP58',  v_designation, 57, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP59',  v_designation, 58, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP60',  v_designation, 59, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP61',  v_designation, 60, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP62',  v_designation, 61, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP63',  v_designation, 62, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP64',  v_designation, 63, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP65',  v_designation, 64, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP66',  v_designation, 65, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP67',  v_designation, 66, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP68',  v_designation, 67, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP69',  v_designation, 68, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP70',  v_designation, 69, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP71',  v_designation, 70, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP72',  v_designation, 71, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP73',  v_designation, 72, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP74',  v_designation, 73, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP75',  v_designation, 74, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP76',  v_designation, 75, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP77',  v_designation, 76, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP78',  v_designation, 77, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP79',  v_designation, 78, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, v_email, true, 'SLIDESHOW', 'RP80',  v_designation, 79, 15);

END $$;
