-- DECLARE VARIABLES (Modify these values for different users)
DECLARE @email VARCHAR(100) = '566217';
DECLARE @designation VARCHAR(100) = 'HO-TOPMGMT';

-- INSERT STATEMENT using variables
INSERT INTO role_reports (
    created_date,
    updated_date,
    active,
    email,
    is_admin,
    mode,
    reportId,
    role_id,
    sequence,
    transition
) VALUES 
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP1', @designation, 1, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP2', @designation, 2, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP3', @designation, 3, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP4', @designation, 4, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP5', @designation, 5, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP6', @designation, 6, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP7', @designation, 7, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP8', @designation, 8, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP9', @designation, 9, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP10', @designation, 10, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP11', @designation, 11, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP12', @designation, 12, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP13', @designation, 13, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP14', @designation, 14, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP15', @designation, 15, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP16', @designation, 16, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP17', @designation, 17, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP18', @designation, 18, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP19', @designation, 19, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP20', @designation, 20, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP21', @designation, 21, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP22', @designation, 22, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP23', @designation, 23, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP24', @designation, 24, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP25', @designation, 25, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP26', @designation, 26, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP27', @designation, 27, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP28', @designation, 28, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP29', @designation, 29, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP30', @designation, 30, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP31', @designation, 31, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP32', @designation, 32, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP33', @designation, 33, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP34', @designation, 34, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP35', @designation, 35, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP36', @designation, 36, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP37', @designation, 37, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP38', @designation, 38, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP39', @designation, 39, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP40', @designation, 40, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP42', @designation, 41, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP43', @designation, 42, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP44', @designation, 43, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP45', @designation, 44, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP46', @designation, 45, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP47', @designation, 46, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP48', @designation, 47, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP49', @designation, 48, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP50', @designation, 49, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP51', @designation, 50, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP52', @designation, 51, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP53', @designation, 52, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP54', @designation, 53, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP55', @designation, 54, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP56', @designation, 55, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP57', @designation, 56, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP58', @designation, 57, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP59', @designation, 58, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP60', @designation, 59, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP61', @designation, 60, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP62', @designation, 61, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP63', @designation, 62, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP64', @designation, 63, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP65', @designation, 64, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP66', @designation, 65, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP67', @designation, 66, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP68', @designation, 67, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP69', @designation, 68, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP70', @designation, 69, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP71', @designation, 70, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP72', @designation, 71, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP73', @designation, 72, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP74', @designation, 73, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP75', @designation, 74, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP76', @designation, 75, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP77', @designation, 76, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP78', @designation, 77, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP79', @designation, 78, 15),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, @email, true, 'SLIDESHOW', 'RP80', @designation, 79, 15);
